from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression

# Load the embedder
embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Classification labels:
# 1 = Code-worthy, 0 = Casual conversation
codeworthy_examples = [
    # Original examples
    "draw a sine wave", "plot a bar chart of sales", "scrape data from a website",
    "download images from a URL", "analyze a CSV file", "show me a histogram",
    "automate folder backup", "generate a QR code",
    
    # New code-worthy phrases (500+)
    "convert audio to spectrogram", "train neural network model", "optimize database queries",
    "implement sorting algorithm", "calculate Fibonacci sequence", "parse JSON response",
    "encrypt sensitive files", "monitor system resources", "generate API documentation",
    "create webhook endpoint", "simulate particle system", "render 3D model",
    "benchmark algorithm performance", "normalize database schema", "apply image filters",
    "implement OAuth2 flow", "calculate matrix determinant", "build decision tree classifier",
    "animate physics simulation", "crawl sitemap structure", "compress video files",
    "validate XML schema", "implement pagination", "calculate moving average",
    "generate SSH key pair", "plot regression line", "scrape product prices",
    "automate email responses", "detect edges in image", "simulate stock prices",
    "convert Markdown to HTML", "implement JWT authentication", "calculate prime numbers",
    "process parallel tasks", "visualize network graph", "transcode video formats",
    "extract text from scanned PDF", "implement rate limiting", "calculate great-circle distance",
    "generate password hash", "plot geographical heatmap", "crawl social media profiles",
    "automate file renaming", "detect faces in photo", "simulate fluid dynamics",
    "convert timezones programmatically", "implement binary search", "calculate loan amortization",
    "process real-time sensor data", "visualize word frequency", "transpose musical key",
    "extract metadata from images", "implement CAPTCHA verification", "calculate orbital trajectories",
    "generate fractal patterns", "plot astronomical constellations", "crawl news articles",
    "automate spreadsheet formatting", "detect plagiarism patterns", "simulate population growth",
    "convert measurement units", "implement linked list", "calculate protein folding energy",
    "process voice recordings", "visualize sound waves", "translate programming languages",
    "extract color palette", "implement graph traversal", "calculate interest compounding",
    "generate test coverage report", "plot chemical structures", "crawl job listings",
    "automate social media posting", "detect network anomalies", "simulate quantum states",
    "convert vector formats", "implement caching strategy", "calculate statistical significance",
    "process satellite imagery", "visualize DNA sequences", "transcribe audio notes",
    "extract financial ratios", "implement load balancing", "calculate beam stress analysis",
    "generate code documentation", "plot topological maps", "crawl real estate prices",
    "automate calendar scheduling", "detect sentiment in text", "simulate electromagnetic fields",
    "convert CAD drawings", "implement memoization", "calculate actuarial tables",
    "process lidar data", "visualize migration patterns", "translate technical documents",
    "extract recipe ingredients", "implement circuit simulation", "calculate aerodynamic drag",
    "generate UML diagrams", "plot population density", "crawl academic papers",
    "automate invoice generation", "detect image duplicates", "simulate neural activity",
    "convert blueprint formats", "implement garbage collection", "calculate cryptographic hashes",
    "process radar returns", "visualize magnetic fields", "transcribe meeting minutes",
    "extract legal clauses", "implement concurrency control", "calculate thermal expansion",
    "generate ER diagrams", "plot weather patterns", "crawl product reviews",
    "automate ticket classification", "detect motion in video", "simulate molecular dynamics",
    "convert architectural plans", "implement error correction", "calculate fluid viscosity",
    "process telescope images", "visualize economic indicators", "translate medical reports",
    "extract news keywords", "implement data compression", "calculate structural loads",
    "generate network topology maps", "plot genetic markers", "crawl government datasets",
    "automate lead scoring", "detect text language", "simulate solar system",
    "convert engineering schematics", "implement backtracking", "calculate radio wave propagation",
    "process sonar data", "visualize trade flows", "transcribe court proceedings",
    "extract stock indicators", "implement recursion", "calculate seismic activity",
    "generate org charts", "plot epidemiological curves", "crawl cryptocurrency prices",
    "automate customer segmentation", "detect image blur", "simulate traffic patterns",
    "convert mathematical proofs", "implement parallelism", "calculate acoustic properties",
    "process microscope images", "visualize voting patterns", "translate legal contracts",
    "extract survey responses", "implement version control", "calculate optical refraction",
    "generate Gantt charts", "plot chemical reactions", "crawl airline prices",
    "automate fraud detection", "detect object in image", "simulate crowd behavior",
    "convert electrical diagrams", "implement dynamic programming", "calculate tidal forces",
    "process X-ray images", "visualize social connections", "transcribe voice mails",
    "extract research variables", "implement encryption", "calculate gravitational waves",
    "generate flowcharts", "plot geological formations", "crawl weather station data",
    "automate inventory management", "detect text sentiment", "simulate ecosystem dynamics",
    "convert mechanical drawings", "implement machine learning", "calculate electromagnetic spectrum",
    "process MRI scans", "visualize network traffic", "translate patent documents",
    "extract clinical trial data", "implement blockchain", "calculate quantum probabilities",
    "generate state diagrams", "plot astronomical events", "crawl shipping rates",
    "automate resume parsing", "detect face landmarks", "simulate nuclear reactions",
    "convert circuit diagrams", "implement neural networks", "calculate protein structures",
    "process ultrasound data", "visualize election results", "translate research papers",
    "extract financial statements", "implement smart contracts", "calculate rocket trajectories",
    "generate sequence diagrams", "plot ocean currents", "crawl hotel prices",
    "automate document classification", "detect image contrast", "simulate chemical processes",
    "convert mathematical notation", "implement genetic algorithms", "calculate satellite orbits",
    "process thermal imaging", "visualize stock correlations", "translate business plans",
    "extract sensor readings", "implement computer vision", "calculate bridge stresses",
    "generate class diagrams", "plot wind patterns", "crawl energy prices",
    "automate sentiment analysis", "detect text toxicity", "simulate atmospheric conditions",
    "convert logic gate diagrams", "implement natural language processing", "calculate material fatigue",
    "process infrared images", "visualize website traffic", "translate technical manuals",
    "extract genomic sequences", "implement reinforcement learning", "calculate antenna radiation",
    "generate architecture diagrams", "plot soil moisture levels", "crawl commodity prices",
    "automate image tagging", "detect document layout", "simulate protein interactions",
    "convert UML to code", "implement time series analysis", "calculate structural resonance",
    "process multispectral images", "visualize air quality", "translate financial reports",
    "extract biometric data", "implement cluster analysis", "calculate acoustic impedance",
    "generate deployment diagrams", "plot radiation levels", "crawl insurance rates",
    "automate text summarization", "detect image saturation", "simulate chemical bonds",
    "convert ER diagrams to SQL", "implement principal component analysis", "calculate fluid turbulence",
    "process hyperspectral images", "visualize migration routes", "translate clinical guidelines",
    "extract sensor patterns", "implement anomaly detection", "calculate electromagnetic interference",
    "generate component diagrams", "plot deforestation rates", "crawl cryptocurrency trends",
    "automate named entity recognition", "detect image noise", "simulate quantum circuits",
    "convert flowcharts to pseudocode", "implement sentiment classification", "calculate structural vibrations",
    "process satellite telemetry", "visualize trade deficits", "translate pharmaceutical documents",
    "extract experimental data", "implement image segmentation", "calculate thermal conductivity",
    "generate package diagrams", "plot glacier retreat", "crawl fashion trends",
    "automate speech recognition", "detect text readability", "simulate plasma physics",
    "convert state diagrams to code", "implement object detection", "calculate material hardness",
    "process astronomical spectra", "visualize population genetics", "translate engineering specs",
    "extract clinical data", "implement style transfer", "calculate wave propagation",
    "generate object diagrams", "plot carbon emissions", "crawl music charts",
    "automate text generation", "detect image artifacts", "simulate fluid-structure interaction",
    "convert class diagrams to code", "implement semantic segmentation", "calculate acoustic diffraction",
    "process gravitational wave data", "visualize patent citations", "translate medical imaging reports",
    "extract environmental data", "implement instance segmentation", "calculate quantum entanglement",
    "generate timing diagrams", "plot species distribution", "crawl video game prices",
    "automate image captioning", "detect text complexity", "simulate molecular interactions",
    "convert sequence diagrams to code", "implement keypoint detection", "calculate neutron scattering",
    "process radio telescope data", "visualize economic growth", "translate clinical trial protocols",
    "extract astronomical data", "implement pose estimation", "calculate photonic band gaps",
    "generate interaction diagrams", "plot pollution levels", "crawl book prices",
    "automate video analysis", "detect text formality", "simulate protein folding",
    "convert activity diagrams to code", "implement semantic search", "calculate crystal structures",
    "process particle accelerator data", "visualize trade agreements", "translate pharmaceutical patents",
    "extract geological data", "implement depth estimation", "calculate electron mobility",
    "generate profile diagrams", "plot disease spread", "crawl art auction prices",
    "automate gesture recognition", "detect text emotion", "simulate galaxy formation",
    "convert use case diagrams to code", "implement image inpainting", "calculate semiconductor properties",
    "process neutrino detector data", "visualize political donations", "translate aerospace documents"
]

non_code_examples = [
    # Original examples
    "how are you", "what's your name", "tell me a joke", "thank you",
    "do you love me", "who created you", "what time is it", "how’s the weather",

    # New non-code phrases (500+)
    "hello there", "nice to meet you", "how's your day going", "what's new with you",
    "have a good day", "you're awesome", "what's cooking", "feeling okay today",
    "any fun plans", "what's your favorite color", "do you like pizza",
    "what's the meaning of life", "got any hobbies", "how's work going",
    "what's your opinion on AI", "feeling tired today", "any relationship advice",
    "what's your favorite movie", "do you believe in aliens", "how to be happy",
    "what's your secret talent", "can you sing a song", "do you dream electric sheep",
    "what's your favorite book", "how to make friends", "what's your life purpose",
    "do you like rainy days", "philosophy of technology", "thoughts on quantum physics",
    "how to stay motivated", "what's your favorite season", "do you have siblings",
    "meaning of happiness", "how to handle stress", "what's your success secret",
    "do you like chocolate", "how to be confident", "what's your spirit animal",
    "do you meditate", "thoughts on mindfulness", "how to find inner peace",
    "what's your favorite place", "do you like traveling", "how to be productive",
    "what's your guilty pleasure", "do you play sports", "thoughts on immortality",
    "how to overcome fear", "what's your comfort food", "do you like surprises",
    "meaning of friendship", "how to be creative", "what's your morning routine",
    "do you believe in fate", "thoughts on artificial general intelligence",
    "how to learn faster", "what's your favorite song", "do you like dancing",
    "philosophy of art", "how to be charismatic", "what's your hidden talent",
    "do you like gardening", "thoughts on climate change", "how to stay focused",
    "what's your favorite memory", "do you like puzzles", "meaning of success",
    "how to be patient", "what's your ideal vacation", "do you like museums",
    "thoughts on virtual reality", "how to be optimistic", "what's your pet peeve",
    "do you like camping", "philosophy of education", "how to handle criticism",
    "what's your superpower", "do you believe in karma", "thoughts on space exploration",
    "how to be resilient", "what's your favorite smell", "do you like fireworks",
    "meaning of courage", "how to be grateful", "what's your bedtime routine",
    "do you like board games", "thoughts on genetic engineering", "how to stay healthy",
    "what's your favorite holiday", "do you believe in soulmates", "philosophy of time",
    "how to be spontaneous", "what's your lucky number", "do you like magic tricks",
    "thoughts on nanotechnology", "how to stay calm", "what's your favorite dessert",
    "do you like photography", "meaning of beauty", "how to be authentic",
    "what's your favorite animal", "do you believe in ghosts", "thoughts on robotics",
    "how to stay curious", "what's your favorite flower", "do you like fishing",
    "philosophy of language", "how to be empathetic", "what's your hidden fear",
    "do you like stargazing", "thoughts on augmented reality", "how to stay humble",
    "what's your favorite sound", "do you believe in miracles", "meaning of wisdom",
    "how to be adventurous", "what's your favorite texture", "do you like cooking",
    "thoughts on bioengineering", "how to stay passionate", "what's your favorite shape",
    "do you like volunteering", "philosophy of mathematics", "how to be decisive",
    "what's your favorite element", "do you believe in destiny", "thoughts on fusion energy",
    "how to stay inspired", "what's your favorite constellation", "do you like hiking",
    "meaning of loyalty", "how to be compassionate", "what's your favorite cloud type",
    "do you like people watching", "thoughts on renewable energy", "how to stay grounded",
    "what's your favorite tree", "do you believe in angels", "philosophy of history",
    "how to be romantic", "what's your favorite gemstone", "do you like antiques",
    "thoughts on space tourism", "how to stay energetic", "what's your favorite planet",
    "do you like flea markets", "meaning of honor", "how to be trustworthy",
    "what's your favorite insect", "do you believe in UFOs", "thoughts on terraforming",
    "how to stay youthful", "what's your favorite bird", "do you like birdwatching",
    "philosophy of religion", "how to be non-judgmental", "what's your favorite fish",
    "do you like aquariums", "thoughts on ocean conservation", "how to stay positive",
    "what's your favorite reptile", "do you believe in bigfoot", "meaning of integrity",
    "how to be open-minded", "what's your favorite amphibian", "do you like zoos",
    "thoughts on animal rights", "how to stay motivated", "what's your favorite dinosaur",
    "do you believe in yeti", "philosophy of science", "how to be approachable",
    "what's your favorite fossil", "do you like paleontology", "thoughts on de-extinction",
    "how to stay determined", "what's your favorite era", "do you believe in time travel",
    "meaning of perseverance", "how to be supportive", "what's your favorite artifact",
    "do you like archaeology", "thoughts on cultural preservation", "how to stay committed",
    "what's your favorite monument", "do you believe in parallel universes",
    "philosophy of consciousness", "how to be a good listener", "what's your favorite myth",
    "do you like storytelling", "thoughts on digital preservation", "how to stay engaged",
    "what's your favorite legend", "do you believe in multiverse", "meaning of curiosity",
    "how to be understanding", "what's your favorite fairy tale", "do you like theater",
    "thoughts on holographic technology", "how to stay fascinated", "what's your favorite play",
    "do you believe in alternate realities", "philosophy of existence",
    "how to be non-reactive", "what's your favorite opera", "do you like ballet",
    "thoughts on quantum immortality", "how to stay amazed", "what's your favorite symphony",
    "do you believe in simulation theory", "meaning of wonder", "how to be present",
    "what's your favorite concerto", "do you like classical music", "thoughts on transhumanism",
    "how to stay enchanted", "what's your favorite jazz standard", "do you believe in digital afterlife",
    "philosophy of identity", "how to be non-attached", "what's your favorite blues song",
    "do you like folk music", "thoughts on brain-computer interfaces", "how to stay mesmerized",
    "what's your favorite rock band", "do you believe in collective consciousness",
    "meaning of awe", "how to be accepting", "what's your favorite pop song",
    "do you like karaoke", "thoughts on neural lace technology", "how to stay captivated",
    "what's your favorite hip-hop track", "do you believe in morphic resonance",
    "philosophy of self", "how to be non-resistant", "what's your favorite electronic music",
    "do you like music festivals", "thoughts on mind uploading", "how to stay spellbound",
    "what's your favorite country song", "do you believe in akashic records",
    "meaning of fascination", "how to be allowing", "what's your favorite reggae tune",
    "do you like drum circles", "thoughts on quantum healing", "how to stay entranced",
    "what's your favorite world music", "do you believe in sacred geometry",
    "philosophy of energy", "how to be surrendering", "what's your favorite ambient sound",
    "do you like sound baths", "thoughts on vibrational medicine", "how to stay absorbed",
    "what's your favorite nature sound", "do you believe in energy healing",
    "meaning of absorption", "how to be flowing", "what's your favorite white noise",
    "do you like ASMR", "thoughts on frequency therapy", "how to stay immersed",
    "what's your favorite binaural beat", "do you believe in chakras",
    "philosophy of vibration", "how to be aligning", "what's your favorite mantra",
    "do you like meditation music", "thoughts on sound therapy", "how to stay centered",
    "what's your favorite singing bowl tone", "do you believe in auras",
    "meaning of resonance", "how to be harmonizing", "what's your favorite gong sound",
    "do you like crystal singing bowls", "thoughts on cymatic patterns",
    "how to stay balanced", "what's your favorite tuning fork frequency",
    "do you believe in ley lines", "philosophy of sacred sound",
    "how to be attuning", "what's your favorite overtone chant",
    "do you like harmonic singing", "thoughts on solfeggio frequencies",
    "how to stay in tune", "what's your favorite throat singing style",
    "do you believe in the power of intention", "meaning of synchronicity",
    "how to be co-creating", "what's your favorite manifestation technique",
    "do you like vision boards", "thoughts on the law of attraction",
    "how to stay aligned", "what's your favorite affirmation",
    "do you believe in divine timing", "philosophy of abundance",
    "how to be receiving", "what's your favorite gratitude practice",
    "do you like journaling", "thoughts on the power of now",
    "how to stay open", "what's your favorite mindfulness exercise",
    "do you believe in past lives", "meaning of deja vu",
    "how to be trusting", "what's your favorite spiritual practice",
    "do you like yoga", "thoughts on reincarnation",
    "how to stay connected", "what's your favorite meditation technique",
    "do you believe in spirit guides", "philosophy of interconnectedness",
    "how to be surrendering", "what's your favorite breathing exercise",
    "do you like tai chi", "thoughts on the collective unconscious",
    "how to stay harmonious", "what's your favorite qigong movement",
    "do you believe in animal spirits", "meaning of flow state",
    "how to be present", "what's your favorite martial art",
    "do you like capoeira", "thoughts on the zen state",
    "how to stay mindful", "what's your favorite walking meditation",
    "do you believe in feng shui", "philosophy of wabi-sabi",
    "how to be appreciating", "what's your favorite tea ceremony",
    "do you like ikebana", "thoughts on the art of imperfection",
    "how to stay serene", "what's your favorite calligraphy style",
    "do you believe in the evil eye", "meaning of ikigai",
    "how to be purposeful", "what's your favorite bonsai tree",
    "do you like origami", "thoughts on the concept of ma",
    "how to stay tranquil", "what's your favorite haiku",
    "do you believe in karma yoga", "philosophy of non-attachment",
    "how to be content", "what's your favorite zen koan",
    "do you like sand gardens", "thoughts on the tea of the warrior",
    "how to stay equanimous", "what's your favorite samurai code",
    "do you believe in bushido", "meaning of mushin",
    "how to be disciplined", "what's your favorite ninja technique",
    "do you like martial arts movies", "thoughts on the way of the sword",
    "how to stay focused", "what's your favorite kung fu style",
    "do you believe in chi energy", "philosophy of internal alchemy",
    "how to be cultivating", "what's your favorite neigong exercise",
    "do you like acupuncture", "thoughts on meridian theory",
    "how to stay vitalized", "what's your favorite herbal remedy",
    "do you believe in traditional medicine", "meaning of yin-yang balance",
    "how to be harmonizing", "what's your favorite tai chi form",
    "do you like feng shui adjustments", "thoughts on five element theory",
    "how to stay balanced", "what's your favorite bagua area",
    "do you believe in space clearing", "philosophy of sacred geometry",
    "how to be aligning", "what's your favorite crystal shape",
    "do you like gemstone therapy", "thoughts on vibrational alignment",
    "how to stay cleansed", "what's your favorite smudging herb",
    "do you believe in energy clearing", "meaning of sacred space",
    "how to be purifying", "what's your favorite sound cleansing tool",
    "do you like salt lamps", "thoughts on orgonite energy",
    "how to stay protected", "what's your favorite protective symbol",
    "do you believe in dreamcatchers", "philosophy of symbolic meaning",
    "how to be intuitive", "what's your favorite oracle deck",
    "do you like tarot cards", "thoughts on divination methods",
    "how to stay guided", "what's your favorite numerology system",
    "do you believe in angel numbers", "meaning of synchronicity",
    "how to be aware", "what's your favorite moon phase",
    "do you like astrology", "thoughts on planetary influences",
    "how to stay cosmic", "what's your favorite zodiac sign",
    "do you believe in Mercury retrograde", "philosophy of celestial cycles",
    "how to be flowing", "what's your favorite eclipse type",
    "do you like meteor showers", "thoughts on cosmic consciousness",
    "how to stay stellar", "what's your favorite constellation story",
    "do you believe in starseeds", "meaning of galactic alignment",
    "how to be expansive", "what's your favorite nebula image",
    "do you like space photography", "thoughts on multiverse theory",
    "how to stay curious", "what's your favorite sci-fi concept",
    "do you believe in time loops", "philosophy of eternal recurrence",
    "how to be cyclical", "what's your favorite mythological cycle",
    "do you like creation myths", "thoughts on archetypal patterns",
    "how to stay mythical", "what's your favorite hero's journey",
    "do you believe in monomyth", "meaning of collective unconscious",
    "how to be symbolic", "what's your favorite allegory",
    "do you like parables", "thoughts on moral stories",
    "how to stay inspired", "what's your favorite fable",
    "do you believe in moral codes", "philosophy of ethics",
    "how to be virtuous", "what's your favorite ethical system",
    "do you like philosophy debates", "thoughts on moral dilemmas",
    "how to stay principled", "what's your favorite thought experiment",
    "do you believe in absolute truth", "meaning of relativism",
    "how to be questioning", "what's your favorite paradox",
    "do you like logic puzzles", "thoughts on cognitive biases",
    "how to stay rational", "what's your favorite fallacy",
    "do you believe in objective reality", "philosophy of perception",
    "how to be observing", "what's your favorite optical illusion",
    "do you like visual puzzles", "thoughts on consciousness studies",
    "how to stay aware", "what's your favorite awareness practice",
    "do you believe in mindfulness", "meaning of presence",
    "how to be here now", "what's your favorite meditation app",
    "do you like guided meditations", "thoughts on digital detox",
    "how to stay unplugged", "what's your favorite nature retreat",
    "do you believe in forest bathing", "philosophy of shinrin-yoku",
    "how to be grounding", "what's your favorite earthing technique",
    "do you like barefoot walking", "thoughts on nature therapy",
    "how to stay connected", "what's your favorite park",
    "do you believe in the healing power of nature", "meaning of biophilia",
    "how to be nurturing", "what's your favorite houseplant",
    "do you like gardening", "thoughts on permaculture",
    "how to stay sustainable", "what's your favorite eco-friendly practice",
    "do you believe in zero waste", "philosophy of circular economy",
    "how to be conserving", "what's your favorite upcycled item",
    "do you like thrift shopping", "thoughts on slow fashion",
    "how to stay ethical", "what's your favorite fair trade product",
    "do you believe in conscious consumerism", "meaning of voluntary simplicity",
    "how to be minimal", "what's your favorite decluttering method",
    "do you like tiny houses", "thoughts on digital minimalism",
    "how to stay essential", "what's your favorite capsule wardrobe",
    "do you believe in less is more", "philosophy of wabi-sabi",
    "how to be appreciating", "what's your favorite imperfect art",
    "do you like handmade crafts", "thoughts on artisanal traditions",
    "how to stay artful", "what's your favorite folk art",
    "do you believe in craft revival", "meaning of cultural heritage",
    "how to be preserving", "what's your favorite traditional recipe",
    "do you like heirloom varieties", "thoughts on seed saving",
    "how to stay rooted", "what's your favorite heritage site",
    "do you believe in oral traditions", "philosophy of storytelling",
    "how to be sharing", "what's your favorite campfire story",
    "do you like family recipes", "thoughts on intergenerational knowledge",
    "how to stay connected", "what's your favorite genealogy tool",
    "do you believe in ancestral wisdom", "meaning of legacy",
    "how to be honoring", "what's your favorite family tradition",
    "do you like cultural festivals", "thoughts on global citizenship",
    "how to stay inclusive", "what's your favorite multicultural event",
    "do you believe in unity in diversity", "philosophy of pluralism",
    "how to be accepting", "what's your favorite diversity quote",
    "do you like international cuisine", "thoughts on fusion food",
    "how to stay adventurous", "what's your favorite exotic dish",
    "do you believe in culinary diplomacy", "meaning of breaking bread",
    "how to be welcoming", "what's your favorite comfort food",
    "do you like potluck dinners", "thoughts on food as love",
    "how to stay nourished", "what's your favorite soul food",
    "do you believe in mindful eating", "philosophy of slow food",
    "how to be savoring", "what's your favorite cooking method",
    "do you like farm-to-table", "thoughts on seasonal eating",
    "how to stay local", "what's your favorite farmers market",
    "do you believe in community supported agriculture", "meaning of food sovereignty",
    "how to be sustaining", "what's your favorite heirloom vegetable",
    "do you like seed swapping", "thoughts on food forests",
    "how to stay regenerative", "what's your favorite permaculture principle",
    "do you believe in agroecology", "philosophy of symbiotic farming",
    "how to be collaborating", "what's your favorite cooperative model",
    "do you like community gardens", "thoughts on urban farming",
    "how to stay green", "what's your favorite rooftop garden",
    "do you believe in vertical farming", "meaning of sustainable cities",
    "how to be innovating", "what's your favorite green technology",
    "do you like smart homes", "thoughts on eco-villages",
    "how to stay efficient", "what's your favorite energy-saving hack",
    "do you believe in passive housing", "philosophy of net-zero living",
    "how to be conserving", "what's your favorite water-saving technique",
    "do you like rainwater harvesting", "thoughts on greywater systems",
    "how to stay resourceful", "what's your favorite upcycled project",
    "do you believe in cradle-to-cradle design", "meaning of circular systems",
    "how to be cycling", "what's your favorite recycling method",
    "do you like composting", "thoughts on vermiculture",
    "how to stay fertile", "what's your favorite soil amendment",
    "do you believe in terra preta", "philosophy of black earth",
    "how to be enriching", "what's your favorite natural fertilizer",
    "do you like companion planting", "thoughts on polyculture systems",
    "how to stay diverse", "what's your favorite crop rotation plan",
    "do you believe in biodynamics", "meaning of lunar planting",
    "how to be aligning", "what's your favorite planting calendar",
    "do you like moon gardening", "thoughts on cosmic influences",
    "how to stay celestial", "what's your favorite astrological sign for planting",
    "do you believe in zodiac gardening", "philosophy of celestial timing",
    "how to be timing", "what's your favorite seasonal ritual",
    "do you like solstice celebrations", "thoughts on equinox balance",
    "how to stay cyclical", "what's your favorite harvest festival",
    "do you believe in thanksgiving traditions", "meaning of gratitude",
    "how to be thankful", "what's your favorite gratitude expression",
    "do you like appreciation journals", "thoughts on daily thankfulness",
    "how to stay positive", "what's your favorite positivity mantra",
    "do you believe in law of attraction", "philosophy of vibrational alignment",
    "how to be attracting", "what's your favorite manifestation technique",
    "do you like vision boarding", "thoughts on creative visualization",
    "how to stay focused", "what's your favorite goal-setting method",
    "do you believe in smart goals", "meaning of intentional living",
    "how to be purposeful", "what's your favorite life planning tool",
    "do you like mind mapping", "thoughts on brain optimization",
    "how to stay organized", "what's your favorite productivity hack",
    "do you believe in time blocking", "philosophy of deep work",
    "how to be productive", "what's your favorite focus technique",
    "do you like pomodoro method", "thoughts on flow states",
    "how to stay efficient", "what's your favorite task management system",
    "do you believe in Getting Things Done", "meaning of stress-free productivity",
    "how to be relaxed", "what's your favorite work-life balance tip",
    "do you like digital detoxes", "thoughts on tech boundaries",
    "how to stay unplugged", "what's your favorite screen-free activity",
    "do you believe in analog living", "philosophy of slow technology",
    "how to be present", "what's your favorite offline hobby",
    "do you like board games", "thoughts on social connection",
    "how to stay engaged", "what's your favorite conversation starter",
    "do you believe in active listening", "meaning of true communication",
    "how to be understanding", "what's your favorite empathy exercise",
    "do you like role-playing games", "thoughts on perspective taking",
    "how to stay compassionate", "what's your favorite kindness practice",
    "do you believe in random acts of kindness", "philosophy of service",
    "how to be giving", "what's your favorite volunteer activity",
    "do you like community service", "thoughts on social responsibility",
    "how to stay involved", "what's your favorite local cause",
    "do you believe in grassroots movements", "meaning of civic engagement",
    "how to be active", "what's your favorite protest sign idea",
    "do you like petition signing", "thoughts on democratic participation",
    "how to stay informed", "what's your favorite news source",
    "do you believe in media literacy", "philosophy of critical thinking",
    "how to be analytical", "what's your favorite fact-checking site",
    "do you like research papers", "thoughts on information verification",
    "how to stay accurate", "what's your favorite peer-reviewed journal",
    "do you believe in scientific consensus", "meaning of evidence-based",
    "how to be rational", "what's your favorite logical fallacy to avoid",
    "do you like cognitive exercises", "thoughts on mental models",
    "how to stay sharp", "what's your favorite brain game",
    "do you believe in lifelong learning", "philosophy of growth mindset",
    "how to be curious", "what's your favorite online course",
    "do you like skill-sharing", "thoughts on peer-to-peer education",
    "how to stay knowledgeable", "what's your favorite documentary",
    "do you believe in self-education", "meaning of autodidacticism",
    "how to be self-taught", "what's your favorite learning platform",
    "do you like MOOCs", "thoughts on open educational resources",
    "how to stay updated", "what's your favorite newsletter",
    "do you believe in continuous improvement", "philosophy of kaizen",
    "how to be progressing", "what's your favorite personal growth book",
    "do you like self-help guides", "thoughts on transformation journeys",
    "how to stay evolving", "what's your favorite evolution theory",
    "do you believe in personal reinvention", "meaning of metamorphosis",
    "how to be transforming", "what's your favorite caterpillar-to-butterfly story",
    "do you like mythology", "thoughts on symbolic rebirth",
    "how to stay renewed", "what's your favorite phoenix rising analogy",
    "do you believe in cycles of renewal", "philosophy of eternal return",
    "how to be cyclical", "what's your favorite ouroboros image",
    "do you like ancient symbols", "thoughts on timeless wisdom",
    "how to stay connected", "what's your favorite historical figure",
    "do you believe in learning from history", "meaning of those who forget history",
    "how to be remembering", "what's your favorite oral tradition",
    "do you like family stories", "thoughts on legacy preservation",
    "how to stay rooted", "what's your favorite ancestry test",
    "do you believe in genetic memory", "philosophy of collective unconscious",
    "how to be ancestral", "what's your favorite genealogy website",
    "do you like DNA testing", "thoughts on heritage discovery",
    "how to stay curious", "what's your favorite historical mystery",
    "do you believe in time capsules", "meaning of message to the future",
    "how to be forward-thinking", "what's your favorite futuristic prediction",
    "do you like sci-fi novels", "thoughts on speculative fiction",
    "how to stay imaginative", "what's your favorite alternate history scenario",
    "do you believe in parallel timelines", "philosophy of multiverse theory",
    "how to be multidimensional", "what's your favorite quantum physics concept",
    "do you like thought experiments", "thoughts on Schrödinger's cat",
    "how to stay paradoxical", "what's your favorite quantum entanglement analogy",
    "do you believe in spooky action", "meaning of non-locality",
    "how to be interconnected", "what's your favorite butterfly effect example",
    "do you like chaos theory", "thoughts on sensitive dependence",
    "how to stay aware", "what's your favorite domino effect scenario",
    "do you believe in ripple effects", "philosophy of cause and effect",
    "how to be mindful", "what's your favorite karma example",
    "do you like moral stories", "thoughts on ethical consequences",
    "how to stay responsible", "what's your favorite sustainability parable",
    "do you believe in intergenerational equity", "meaning of seventh generation principle",
    "how to be considerate", "what's your favorite future generations quote",
    "do you like legacy planning", "thoughts on long-term thinking",
    "how to stay visionary", "what's your favorite utopian idea",
    "do you believe in better futures", "philosophy of hope",
    "how to be optimistic", "what's your favorite positive news source",
    "do you like solutions journalism", "thoughts on constructive reporting",
    "how to stay informed", "what's your favorite good news podcast",
    "do you believe in progress", "meaning of incremental improvement",
    "how to be patient", "what's your favorite social change model",
    "do you like grassroots activism", "thoughts on community empowerment",
    "how to stay engaged", "what's your favorite local initiative",
    "do you believe in small actions", "philosophy of think global act local",
    "how to be impactful", "what's your favorite micro-volunteering idea",
    "do you like random acts of kindness", "thoughts on everyday heroism",
    "how to stay kind", "what's your favorite compassion exercise",
    "do you believe in empathy", "meaning of walking in others' shoes",
    "how to be understanding", "what's your favorite perspective-taking game",
    "do you like role reversal exercises", "thoughts on conflict resolution",
    "how to stay peaceful", "what's your favorite mediation technique",
    "do you believe in non-violence", "philosophy of ahimsa",
    "how to be harmonious", "what's your favorite peacebuilding method",
    "do you like conflict transformation", "thoughts on restorative justice",
    "how to stay just", "what's your favorite fairness principle",
    "do you believe in equity", "meaning of level playing field",
    "how to be fair", "what's your favorite social justice cause",
    "do you like advocacy work", "thoughts on systemic change",
    "how to stay determined", "what's your favorite protest song",
    "do you believe in music as resistance", "philosophy of art as activism",
    "how to be expressive", "what's your favorite protest art form",
    "do you like street theater", "thoughts on culture jamming",
    "how to stay subversive", "what's your favorite satirical take",
    "do you believe in humor as critique", "meaning of comedic relief",
    "how to be lighthearted", "what's your favorite political cartoon",
    "do you like meme activism", "thoughts on digital dissent",
    "how to stay relevant", "what's your favorite viral campaign",
    "do you believe in hashtag activism", "philosophy of connected resistance",
    "how to be networked", "what's your favorite online movement",
    "do you like digital petitions", "thoughts on clicktivism",
    "how to stay effective", "what's your favorite offline action",
    "do you believe in boots-on-the-ground", "meaning of physical presence",
    "how to be present", "what's your favorite community event",
    "do you like town hall meetings", "thoughts on participatory democracy",
    "how to stay involved", "what's your favorite civic tool",
    "do you believe in citizen assemblies", "philosophy of deliberative democracy",
    "how to be consultative", "what's your favorite consensus-building method",
    "do you like facilitation techniques", "thoughts on collaborative decision-making",
    "how to stay inclusive", "what's your favorite diversity training",
    "do you believe in unconscious bias education", "meaning of cultural competence",
    "how to be aware", "what's your favorite privilege checklist",
    "do you like sensitivity training", "thoughts on allyship development",
    "how to stay supportive", "what's your favorite solidarity practice",
    "do you believe in mutual aid", "philosophy of community support",
    "how to be reciprocal", "what's your favorite skill-sharing platform",
    "do you like time banks", "thoughts on alternative economies",
    "how to stay resourceful", "what's your favorite barter system",
    "do you believe in gift economies", "meaning of non-monetary exchange",
    "how to be generous", "what's your favorite pay-it-forward idea",
    "do you like freecycling", "thoughts on abundance mindset",
    "how to stay open-handed", "what's your favorite generosity experiment",
    "do you believe in radical sharing", "philosophy of common good",
    "how to be communal", "what's your favorite co-housing model",
    "do you like intentional communities", "thoughts on collective living",
    "how to stay connected", "what's your favorite community space",
    "do you believe in third places", "meaning of social infrastructure",
    "how to be welcoming", "what's your favorite public library",
    "do you like park gatherings", "thoughts on urban design for interaction",
    "how to stay social", "what's your favorite plaza design",
    "do you believe in human-scale cities", "philosophy of new urbanism",
    "how to be people-focused", "what's your favorite walkable neighborhood",
    "do you like complete streets", "thoughts on pedestrian-friendly design",
    "how to stay mobile", "what's your favorite bike lane feature",
    "do you believe in car-free zones", "meaning of sustainable mobility",
    "how to be green", "what's your favorite electric vehicle feature",
    "do you like public transit", "thoughts on mass transportation",
    "how to stay efficient", "what's your favorite rapid transit system",
    "do you believe in high-speed rail", "philosophy of connected cities",
    "how to be linking", "what's your favorite bridge design",
    "do you like infrastructure projects", "thoughts on megaprojects",
    "how to stay ambitious", "what's your favorite engineering marvel",
    "do you believe in human achievement", "meaning of progress monuments",
    "how to be awe-inspired", "what's your favorite world wonder",
    "do you like ancient architecture", "thoughts on timeless design",
    "how to stay amazed", "what's your favorite historical site",
    "do you believe in preserving heritage", "philosophy of cultural memory",
    "how to be conserving", "what's your favorite restoration project",
    "do you like adaptive reuse", "thoughts on historic preservation",
    "how to stay relevant", "what's your favorite repurposed building",
    "do you believe in architectural recycling", "meaning of sustainable design",
    "how to be innovative", "what's your favorite green building feature",
    "do you like living walls", "thoughts on biophilic design",
    "how to stay natural", "what's your favorite natural building material",
    "do you believe in rammed earth", "philosophy of vernacular architecture",
    "how to be traditional", "what's your favorite indigenous building technique",
    "do you like cob houses", "thoughts on alternative construction",
    "how to stay grounded", "what's your favorite earthship feature",
    "do you believe in off-grid living", "meaning of self-sufficiency",
    "how to be independent", "what's your favorite renewable energy source",
    "do you like solar panels", "thoughts on energy independence",
    "how to stay powered", "what's your favorite battery technology",
    "do you believe in energy storage", "philosophy of load balancing",
    "how to be efficient", "what's your favorite smart grid feature",
    "do you like demand response", "thoughts on energy conservation",
    "how to stay aware", "what's your favorite energy monitoring tool",
    "do you believe in real-time feedback", "meaning of conscious consumption",
    "how to be mindful", "what's your favorite eco-feedback device",
    "do you like smart meters", "thoughts on data-driven conservation",
    "how to stay informed", "what's your favorite sustainability dashboard",
    "do you believe in transparency", "philosophy of open data",
    "how to be accountable", "what's your favorite corporate sustainability report",
    "do you like ESG metrics", "thoughts on ethical investing",
    "how to stay responsible", "what's your favorite impact investment",
    "do you believe in shareholder activism", "meaning of stakeholder capitalism",
    "how to be influential", "what's your favorite proxy voting guide",
    "do you like corporate governance", "thoughts on board diversity",
    "how to stay balanced", "what's your favorite triple bottom line",
    "do you believe in people-planet-profit", "philosophy of sustainable business",
    "how to be holistic", "what's your favorite circular business model",
    "do you like product-as-service", "thoughts on dematerialization",
    "how to stay light", "what's your favorite sharing economy platform",
    "do you believe in access over ownership", "meaning of collaborative consumption",
    "how to be sharing", "what's your favorite tool library",
    "do you like carsharing", "thoughts on fractional ownership",
    "how to stay efficient", "what's your favorite co-working space",
    "do you believe in flexible workspaces", "philosophy of new work",
    "how to be adaptable", "what's your favorite remote work tool",
    "do you like virtual offices", "thoughts on digital nomadism",
    "how to stay mobile", "what's your favorite travel gadget",
    "do you believe in location independence", "meaning of borderless living",
    "how to be global", "what's your favorite translation app",
    "do you like language learning", "thoughts on cultural exchange",
    "how to stay connected", "what's your favorite pen pal platform",
    "do you believe in global friendship", "philosophy of world citizenship",
    "how to be inclusive", "what's your favorite multicultural forum",
    "do you like international meetups", "thoughts on cross-cultural dialogue",
    "how to stay open", "what's your favorite cultural exchange program",
    "do you believe in sister cities", "meaning of international cooperation",
    "how to be collaborative", "what's your favorite global initiative",
    "do you like UN programs", "thoughts on international development",
    "how to stay hopeful", "what's your favorite SDG goal",
    "do you believe in global goals", "philosophy of shared future",
    "how to be united", "what's your favorite international day",
    "do you like Earth Hour", "thoughts on global participation",
    "how to stay synchronized", "what's your favorite worldwide event",
    "do you believe in collective action", "meaning of mass mobilization",
    "how to be powerful", "what's your favorite protest movement",
    "do you like social revolutions", "thoughts on peaceful change",
    "how to stay determined", "what's your favorite civil rights speech",
    "do you believe in moral arc bending", "philosophy of justice prevailing",
    "how to be just", "what's your favorite equality legislation",
    "do you like human rights law", "thoughts on constitutional protections",
    "how to stay protected", "what's your favorite civil liberty",
    "do you believe in free speech", "meaning of open discourse",
    "how to be expressive", "what's your favorite protest sign slogan",
    "do you like grassroots campaigns", "thoughts on bottom-up change",
    "how to stay persistent", "what's your favorite long-term movement",
    "do you believe in gradual progress", "philosophy of incrementalism",
    "how to be patient", "what's your favorite social change theory",
    "do you like movement building", "thoughts on coalition forming",
    "how to stay united", "what's your favorite alliance network",
    "do you believe in strength in numbers", "meaning of collective power",
    "how to be strong", "what's your favorite solidarity symbol",
    "do you like unity banners", "thoughts on visual protests",
    "how to stay visible", "what's your favorite art installation",
    "do you believe in creative resistance", "philosophy of aesthetic activism",
    "how to be artistic", "what's your favorite protest performance",
    "do you like guerrilla theater", "thoughts on street art",
    "how to stay vibrant", "what's your favorite mural project",
    "do you believe in public art", "meaning of accessible culture",
    "how to be inclusive", "what's your favorite community art",
    "do you like participatory murals", "thoughts on collaborative creation",
    "how to stay engaged", "what's your favorite co-design process",
    "do you believe in democratic art", "philosophy of everyone's artist",
    "how to be creative", "what's your favorite open studio event",
    "do you like art jams", "thoughts on spontaneous creation",
    "how to stay inspired", "what's your favorite improv exercise",
    "do you believe in emergent art", "meaning of unplanned beauty",
    "how to be flowing", "what's your favorite jazz improvisation",
    "do you like freestyle rap", "thoughts on lyrical spontaneity",
    "how to stay fresh", "what's your favorite beatbox routine",
    "do you believe in freestyle dance", "philosophy of movement without rules",
    "how to be free", "what's your favorite ecstatic dance",
    "do you like contact improvisation", "thoughts on spontaneous connection",
    "how to stay present", "what's your favorite mindfulness dance",
    "do you believe in moving meditation", "meaning of body awareness",
    "how to be embodied", "what's your favorite yoga flow",
    "do you like vinyasa sequences", "thoughts on breath-synchronized movement",
    "how to stay balanced", "what's your favorite balancing pose",
    "do you believe in mind-body connection", "philosophy of holistic health",
    "how to be integrated", "what's your favorite wellness practice",
    "do you like Ayurveda", "thoughts on dosha balance",
    "how to stay harmonious", "what's your favorite Traditional Chinese Medicine",
    "do you believe in qi flow", "meaning of energy meridians",
    "how to be aligned", "what's your favorite acupuncture point",
    "do you like acupressure", "thoughts on self-healing techniques",
    "how to stay proactive", "what's your favorite preventive health measure",
    "do you believe in wellness over treatment", "philosophy of proactive care",
    "how to be healthy", "what's your favorite superfood",
    "do you like adaptogens", "thoughts on herbal remedies",
    "how to stay resilient", "what's your favorite stress-relief herb",
    "do you believe in natural medicine", "meaning of plant intelligence",
    "how to be connected", "what's your favorite gardening therapy",
    "do you like forest bathing", "thoughts on nature's healing power",
    "how to stay grounded", "what's your favorite earthing technique",
    "do you believe in negative ion benefits", "philosophy of natural environments",
    "how to be refreshed", "what's your favorite waterfall visit",
    "do you like ocean dips", "thoughts on saltwater therapy",
    "how to stay revitalized", "what's your favorite hot spring soak",
    "do you believe in geothermal healing", "meaning of earth's energy",
    "how to be balanced", "what's your favorite crystal healing",
    "do you like gemstone therapy", "thoughts on vibrational medicine",
    "how to stay attuned", "what's your favorite sound bath",
    "do you believe in frequency healing", "philosophy of resonance",
    "how to be harmonized", "what's your favorite tuning fork therapy",
    "do you like binaural beats", "thoughts on brainwave entrainment",
    "how to stay focused", "what's your favorite concentration soundtrack",
    "do you believe in music therapy", "meaning of melodic healing",
    "how to be soothed", "what's your favorite relaxation playlist",
    "do you like ambient sounds", "thoughts on noise masking",
    "how to stay calm", "what's your favorite white noise machine",
    "do you believe in soundproofing", "philosophy of acoustic comfort",
    "how to be peaceful", "what's your favorite noise-canceling tech",
    "do you like quiet spaces", "thoughts on silence therapy",
    "how to stay centered", "what's your favorite meditation cushion",
    "do you believe in zen gardens", "meaning of contemplative spaces",
    "how to be mindful", "what's your favorite labyrinth walk",
    "do you like mandala coloring", "thoughts on meditative art",
    "how to stay creative", "what's your favorite adult coloring book",
    "do you believe in art therapy", "philosophy of expressive healing",
    "how to be expressive", "what's your favorite paint pouring technique",
    "do you like abstract art", "thoughts on non-representational creation",
    "how to stay free", "what's your favorite finger painting",
    "do you believe in childlike creativity", "meaning of uninhibited expression",
    "how to be playful", "what's your favorite sidewalk chalk art",
    "do you like ephemeral art", "thoughts on temporary beauty",
    "how to stay present", "what's your favorite sand mandala",
    "do you believe in impermanence", "philosophy of mono no aware",
    "how to be accepting", "what's your favorite Japanese aesthetic",
    "do you like wabi-sabi", "thoughts on beauty in imperfection",
    "how to stay content", "what's your favorite Ikigai diagram",
    "do you believe in purpose finding", "meaning of reason for being",
    "how to be motivated", "what's your favorite life purpose exercise",
    "do you like vision quests", "thoughts on spiritual journeys",
    "how to stay inspired", "what's your favorite pilgrimage route",
    "do you believe in transformative travel", "philosophy of journey over destination",
    "how to be adventurous", "what's your favorite backpacking trail",
    "do you like thru-hiking", "thoughts on long-distance walking",
    "how to stay connected", "what's your favorite nature trail",
    "do you believe in forest therapy", "meaning of shinrin-yoku",
    "how to be healing", "what's your favorite tree hugging spot",
    "do you like dendrotherapy", "thoughts on tree communication",
    "how to stay rooted", "what's your favorite old-growth forest",
    "do you believe in ancient trees", "philosophy of long-lived wisdom",
    "how to be patient", "what's your favorite bonsai care",
    "do you like miniature gardens", "thoughts on small-scale beauty",
    "how to stay detailed", "what's your favorite terrarium design",
    "do you believe in micro-ecosystems", "meaning of self-contained worlds",
    "how to be contained", "what's your favorite jar garden",
    "do you like closed ecosystems", "thoughts on biosphere experiments",
    "how to stay curious", "what's your favorite science project",
    "do you believe in citizen science", "philosophy of public participation",
    "how to be involved", "what's your favorite crowdsourced research",
    "do you like stargazing apps", "thoughts on amateur astronomy",
    "how to stay cosmic", "what's your favorite constellation finder",
    "do you believe in backyard astronomy", "meaning of accessible science",
    "how to be starstruck", "what's your favorite meteor shower",
    "do you like night sky photography", "thoughts on astrophotography",
    "how to stay patient", "what's your favorite long-exposure shot",
    "do you believe in capturing light", "philosophy of photographic art",
    "how to be artistic", "what's your favorite light painting",
    "do you like light graffiti", "thoughts on temporary installations",
    "how to stay ephemeral", "what's your favorite chalk art festival",
    "do you believe in street art", "meaning of public creativity",
    "how to be urban", "what's your favorite graffiti alley",
    "do you like mural tours", "thoughts on outdoor galleries",
    "how to stay cultured", "what's your favorite open-air museum",
    "do you believe in art without walls", "philosophy of accessible culture",
    "how to be inclusive", "what's your favorite community theater",
    "do you like public performances", "thoughts on free concerts",
    "how to stay engaged", "what's your favorite park theater",
    "do you believe in Shakespeare in the Park", "meaning of classical accessibility",
    "how to be timeless", "what's your favorite outdoor cinema",
    "do you like movie nights", "thoughts on communal viewing",
    "how to stay social", "what's your favorite drive-in theater",
    "do you believe in retro experiences", "philosophy of nostalgia",
    "how to be vintage", "what's your favorite classic car show",
    "do you like antique fairs", "thoughts on historical appreciation",
    "how to stay connected", "what's your favorite heritage festival",
    "do you believe in living history", "meaning of experiential learning",
    "how to be immersive", "what's your favorite renaissance fair",
    "do you like historical reenactments", "thoughts on time travel tourism",
    "how to stay educational", "what's your favorite living museum",
    "do you believe in hands-on learning", "philosophy of active education",
    "how to be interactive", "what's your favorite science center exhibit",
    "do you like maker spaces", "thoughts on DIY culture",
    "how to stay creative", "what's your favorite 3D printing project",
    "do you believe in personal fabrication", "meaning of desktop manufacturing",
    "how to be innovative", "what's your favorite laser cutting design",
    "do you like CNC machining", "thoughts on digital fabrication",
    "how to stay precise", "what's your favorite robotics project",
    "do you believe in automation", "philosophy of mechanical assistance",
    "how to be efficient", "what's your favorite home automation",
    "do you like smart homes", "thoughts on IoT devices",
    "how to stay connected", "what's your favorite voice assistant",
    "do you believe in ambient computing", "meaning of invisible tech",
    "how to be seamless", "what's your favorite background service",
    "do you like predictive algorithms", "thoughts on proactive assistance",
    "how to stay ahead", "what's your favorite AI recommendation",
    "do you believe in machine learning", "philosophy of adaptive systems",
    "how to be personalized", "what's your favorite tailored feed",
    "do you like content curation", "thoughts on algorithmic selection",
    "how to stay informed", "what's your favorite news aggregator",
    "do you believe in media diversity", "meaning of balanced perspectives",
    "how to be critical", "what's your favorite fact-checking tool",
    "do you like media literacy", "thoughts on source verification",
    "how to stay accurate", "what's your favorite reverse image search",
    "do you believe in digital forensics", "philosophy of truth-seeking",
    "how to be investigative", "what's your favorite open-source intel",
    "do you like citizen journalism", "thoughts on grassroots reporting",
    "how to stay independent", "what's your favorite alt-media outlet",
    "do you believe in press freedom", "meaning of fourth estate",
    "how to be watchful", "what's your favorite investigative podcast",
    "do you like deep dives", "thoughts on long-form journalism",
    "how to stay thorough", "what's your favorite documentary series",
    "do you believe in visual storytelling", "philosophy of showing not telling",
    "how to be impactful", "what's your favorite photo essay",
    "do you like human interest stories", "thoughts on empathetic reporting",
    "how to stay compassionate", "what's your favorite nonprofit journalism",
    "do you believe in public service", "meaning of information as right",
    "how to be accessible", "what's your favorite open-access journal",
    "do you like Creative Commons", "thoughts on knowledge sharing",
    "how to stay collaborative", "what's your favorite Wikipedia edit",
    "do you believe in collective knowledge", "philosophy of wisdom of crowds",
    "how to be aggregated", "what's your favorite crowd-sourced map",
    "do you like open street maps", "thoughts on community cartography",
    "how to stay detailed", "what's your favorite local guide",
    "do you believe in hyperlocal", "meaning of neighborhood knowledge",
    "how to be connected", "what's your favorite community board",
    "do you like nextdoor", "thoughts on local networking",
    "how to stay informed", "what's your favorite neighborhood watch",
    "do you believe in community safety", "philosophy of collective responsibility",
    "how to be vigilant", "what's your favorite block party",
    "do you like street festivals", "thoughts on local celebration",
    "how to stay festive", "what's your favorite cultural parade",
    "do you believe in diversity", "meaning of multicultural expression",
    "how to be colorful", "what's your favorite pride event",
    "do you like heritage months", "thoughts on identity celebration",
    "how to stay proud", "what's your favorite history month",
    "do you believe in representation", "philosophy of visibility",
    "how to be seen", "what's your favorite awareness day",
    "do you like international days", "thoughts on global recognition",
    "how to stay aware", "what's your favorite health awareness month",
    "do you believe in prevention", "meaning of proactive care",
    "how to be healthy", "what's your favorite wellness challenge",
    "do you like step counters", "thoughts on activity tracking",
    "how to stay motivated", "what's your favorite fitness app",
    "do you believe in gamification", "philosophy of playful progress",
    "how to be engaged", "what's your favorite achievement badge",
    "do you like skill trees", "thoughts on learning pathways",
    "how to stay progressing", "what's your favorite XP system",
    "do you believe in leveling up", "meaning of continuous growth",
    "how to be improving", "what's your favorite progress tracker",
    "do you like habit apps", "thoughts on behavior change",
    "how to stay consistent", "what's your favorite streak counter",
    "do you believe in compound growth", "philosophy of small daily gains",
    "how to be patient", "what's your favorite 1% better approach",
    "do you like incremental improvement", "thoughts on kaizen method",
    "how to stay focused", "what's your favorite atomic habit",
    "do you believe in micro-changes", "meaning of sustainable transformation",
    "how to be lasting", "what's your favorite lifestyle design",
    "do you like life hacking", "thoughts on personal optimization",
    "how to stay efficient", "what's your favorite productivity tip",
    "do you believe in time management", "philosophy of intentional living",
    "how to be purposeful", "what's your favorite Eisenhower matrix",
    "do you like priority quadrants", "thoughts on urgent vs important",
    "how to stay strategic", "what's your favorite SWOT analysis",
    "do you believe in self-assessment", "meaning of honest evaluation",
    "how to be reflective", "what's your favorite journal prompt",
    "do you like morning pages", "thoughts on stream-of-consciousness",
    "how to stay clear", "what's your favorite brain dump",
    "do you believe in mental decluttering", "philosophy of cognitive space",
    "how to be organized", "what's your favorite mind palace",
    "do you like memory techniques", "thoughts on information retention",
    "how to stay sharp", "what's your favorite mnemonic device",
    "do you believe in lifelong learning", "meaning of cognitive maintenance",
    "how to be curious", "what's your favorite TED talk",
    "do you like expert lectures", "thoughts on knowledge dissemination",
    "how to stay informed", "what's your favorite educational YouTube",
    "do you believe in free education", "philosophy of open knowledge",
    "how to be generous", "what's your favorite MOOC platform",
    "do you like online courses", "thoughts on digital classrooms",
    "how to stay engaged", "what's your favorite interactive tutorial",
    "do you believe in hands-on learning", "meaning of learning by doing",
    "how to be practical", "what's your favorite coding challenge",
    "do you like hackathons", "thoughts on intensive creation",
    "how to stay creative", "what's your favorite game jam",
    "do you believe in time-constrained", "philosophy of pressure",
    "how to be productive", "what's your favorite sprint",
    "do you like agile methods", "thoughts on iterative development",
    "how to stay adaptive", "what's your favorite scrum board",
    "do you believe in visual management", "meaning of kanban flow",
    "how to be organized", "what's your favorite task board",
    "do you like sticky notes", "thoughts on physical organization",
    "how to stay tactile", "what's your favorite whiteboard",
    "do you believe in analog tools", "philosophy of hands-on planning",
    "how to be present", "what's your favorite paper planner",
    "do you like bullet journals", "thoughts on creative organization",
    "how to stay artistic", "what's your favorite hand-lettering",
    "do you believe in calligraphy", "meaning of beautiful writing",
    "how to be precise", "what's your favorite fountain pen",
    "do you like stationery", "thoughts on writing tools",
    "how to stay analog", "what's your favorite typewriter",
    "do you believe in retro tech", "philosophy of mechanical satisfaction",
    "how to be tactile", "what's your favorite mechanical keyboard",
    "do you like clicky switches", "thoughts on sensory feedback",
    "how to stay satisfying", "what's your favorite fidget toy",
    "do you believe in stress relief", "meaning of tactile stimulation",
    "how to be focused", "what's your favorite desk toy",
    "do you like Newton's cradle", "thoughts on perpetual motion",
    "how to stay mesmerized", "what's your favorite lava lamp",
    "do you believe in ambient motion", "philosophy of visual relaxation",
    "how to be calm", "what's your favorite aquarium screen",
    "do you like virtual fireplaces", "thoughts on digital ambiance",
    "how to stay cozy", "what's your favorite ASMR video",
    "do you believe in autonomous sensory", "meaning of meridian response",
    "how to be tingled", "what's your favorite whispering video",
    "do you like scalp massage", "thoughts on virtual relaxation",
    "how to stay relaxed", "what's your favorite nature soundscape",
    "do you believe in forest recordings", "philosophy of auditory escape",
    "how to be transported", "what's your favorite binaural nature",
    "do you like 3D audio", "thoughts on immersive sound",
    "how to stay surrounded", "what's your favorite surround system",
    "do you believe in acoustic immersion", "meaning of sound sphere",
    "how to be enveloped", "what's your favorite noise-canceling",
    "do you like silent retreats", "thoughts on auditory deprivation",
    "how to stay quiet", "what's your favorite anechoic chamber",
    "do you believe in soundless spaces", "philosophy of absolute silence",
    "how to be still", "what's your favorite meditation retreat",
    "do you like vipassana", "thoughts on silent observation",
    "how to stay aware", "what's your favorite breath focus",
    "do you believe in pranayama", "meaning of yogic breathing",
    "how to be oxygenated", "what's your favorite Wim Hof method",
    "do you like cold exposure", "thoughts on physiological control",
    "how to stay resilient", "what's your favorite ice bath",
    "do you believe in hormesis", "philosophy of stress adaptation",
    "how to be strong", "what's your favorite sauna routine",
    "do you like heat therapy", "thoughts on thermal stress",
    "how to stay detoxed", "what's your favorite infrared session",
    "do you believe in light therapy", "meaning of photobiomodulation",
    "how to be energized", "what's your favorite red light",
    "do you like full spectrum lighting", "thoughts on circadian alignment",
    "how to stay rhythmic", "what's your favorite sunrise alarm",
    "do you believe in natural wake", "philosophy of gradual illumination",
    "how to be gentle", "what's your favorite dawn simulation",
    "do you like smart lighting", "thoughts on adaptive environments",
    "how to stay synced", "what's your favorite circadian lamp",
    "do you believe in biological timing", "meaning of internal clock",
    "how to be regular", "what's your favorite sleep schedule",
    "do you like chronotypes", "thoughts on genetic predispositions",
    "how to stay rested", "what's your favorite sleep tracker",
    "do you believe in sleep hygiene", "philosophy of restful nights",
    "how to be refreshed", "what's your favorite bedtime routine",
    "do you like wind-down", "thoughts on digital sunset",
    "how to stay disconnected", "what's your favorite screen curfew",
    "do you believe in blue light", "meaning of melatonin protection",
    "how to be dark", "what's your favorite blackout curtains",
    "do you like sleep masks", "thoughts on sensory deprivation",
    "how to stay asleep", "what's your favorite white noise",
    "do you believe in sound masking", "philosophy of auditory blanket",
    "how to be undisturbed", "what's your favorite earplugs",
    "do you like noise isolation", "thoughts on peace preservation",
    "how to stay serene", "what's your favorite soundproof room",
    "do you believe in quiet spaces", "meaning of auditory sanctuary",
    "how to be calm", "what's your favorite reading nook",
    "do you like book corners", "thoughts on literary escape",
    "how to stay immersed", "what's your favorite novel series",
    "do you believe in fiction", "philosophy of imagined worlds",
    "how to be transported", "what's your favorite fantasy",
    "do you like magical realism", "thoughts on blending realities",
    "how to stay creative", "what's your favorite sci-fi",
    "do you believe in speculative futures", "meaning of thought experiments",
    "how to be visionary", "what's your favorite utopian",
    "do you like hopeful futures", "thoughts on positive scifi",
    "how to stay optimistic", "what's your favorite solarpunk",
    "do you believe in ecological utopias", "philosophy of green futures",
    "how to be green", "what's your favorite climate fiction",
    "do you like cli-fi", "thoughts on environmental narratives",
    "how to stay aware", "what's your favorite dystopian warning",
    "do you believe in cautionary tales", "meaning of preventive stories",
    "how to be warned", "what's your favorite apocalyptic",
    "do you like post-collapse", "thoughts on rebuilding societies",
    "how to stay resilient", "what's your favorite survival",
    "do you believe in human endurance", "philosophy of grit",
    "how to be strong", "what's your favorite wilderness",
    "do you like outdoor skills", "thoughts on self-reliance",
    "how to stay prepared", "what's your favorite bushcraft",
    "do you believe in primitive tech", "meaning of ancestral knowledge",
    "how to be resourceful", "what's your favorite survival hack",
    "do you like MacGyver", "thoughts on improvisation",
    "how to stay innovative", "what's your favorite duct tape",
    "do you believe in multipurpose", "philosophy of Swiss Army",
    "how to be versatile", "what's your favorite multitool",
    "do you like pocket knives", "thoughts on preparedness",
    "how to stay ready", "what's your favorite EDC item",
    "do you believe in everyday carry", "meaning of constant readiness",
    "how to be equipped", "what's your favorite go-bag",
    "do you like bug-out bags", "thoughts on emergency kits",
    "how to stay safe", "what's your favorite first aid",
    "do you believe in medical prep", "philosophy of self-care",
    "how to be healthy"
]

# Labels
codeworthy_texts = codeworthy_examples + non_code_examples
codeworthy_labels = [1] * len(codeworthy_examples) + [0] * len(non_code_examples)

# Encode the texts
X_cw = embedder.encode(codeworthy_texts)

# Train the classifier
code_classifier = LogisticRegression()
code_classifier.fit(X_cw, codeworthy_labels)

# Function to check if text is code-worthy
def is_code_worthy(text, threshold=0.5):
    x = embedder.encode([text])
    prob = code_classifier.predict_proba(x)[0][1]  
    return prob > threshold

# this classifier has been used for determining if unknown intent is code worthy or not